import { StyleSheet } from "react-native";

export const weatherTabStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "#e3f0ff",
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#007AFF",
    marginBottom: 32,
    letterSpacing: 1.5,
  },
  input: {
    borderWidth: 1,
    borderColor: "#007AFF",
    borderRadius: 8,
    padding: 12,
    width: 240,
    marginBottom: 18,
    backgroundColor: "#fff",
    fontSize: 18,
    color: "#222",
    textAlign: "center",
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonWrapper: {
    width: 240,
    marginBottom: 24,
    borderRadius: 8,
    overflow: "hidden",
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  emoji: {
    fontSize: 64,
    marginBottom: 8,
  },
  emojiContainer: {
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  weatherInfo: {
    alignItems: "center",
    marginTop: 20,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  temperature: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#007AFF",
    marginBottom: 8,
  },
  description: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
    textAlign: "center",
  },
  windSpeed: {
    fontSize: 16,
    color: "#666",
  },
  errorContainer: {
    marginTop: 20,
    backgroundColor: "rgba(255, 0, 0, 0.1)",
    borderRadius: 8,
    padding: 16,
    borderColor: "#d00",
    borderWidth: 1,
  },
  errorText: {
    color: "#d00",
    marginBottom: 8,
    textAlign: "center",
    paddingHorizontal: 20,
  },
});
